import html,json,math

def render_cycle(source,prefix):
 stages=json.loads((source/'cycle.json').read_text())
 nodes=[];arcs=[];panels=[]
 for i,s in enumerate(stages):
  angle=math.radians(-90+i*60);x=50+34*math.cos(angle);y=50+37*math.sin(angle)
  a=angle+math.radians(17);b=angle+math.radians(43)
  x1,y1=300+204*math.cos(a),280+207*math.sin(a)
  x2,y2=300+204*math.cos(b),280+207*math.sin(b)
  arc=f"M{x1:.1f},{y1:.1f} A204,207 0 0 1 {x2:.1f},{y2:.1f}"
  arcs.append(f'<path d="{arc}" marker-end="url(#{prefix}-arrow)"/><path d="{arc}" class="cycle-flow" data-cycle-flow="{i}" pathLength="100"/>')
  nodes.append(f'<button type="button" role="tab" id="{prefix}-tab-{i}" class="cycle-node" data-cycle-step="{i}" aria-controls="{prefix}-panel-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}" style="--node-x:{x:.2f}%;--node-y:{y:.2f}%"><span class="node-number">0{i+1}</span><span>{s["short"]}</span></button>')
  panels.append(f'<section class="cycle-panel" id="{prefix}-panel-{i}" role="tabpanel" aria-labelledby="{prefix}-tab-{i}" tabindex="0" {"hidden" if i else ""}><div class="cycle-panel-heading"><span class="eyebrow">0{i+1} / {html.escape(s["moment"])}</span><h2>{html.escape(s["title"])}</h2></div><dl class="cycle-explanation"><div><dt>EL PROBLEMA</dt><dd>{html.escape(s["problem"])}</dd></div><div><dt>QUÈ FA NINTEC360</dt><dd>{html.escape(s["action"])}</dd></div><div><dt>QUÈ HI GUANYES</dt><dd>{html.escape(s["benefit"])}</dd></div></dl><p class="cycle-record"><span>AL CRM</span> {html.escape(s["record"])}</p></section>')
 nodes.append(f'<button type="button" role="tab" id="{prefix}-tab-6" class="cycle-center" data-cycle-step="6" aria-controls="{prefix}-panel-6" aria-selected="false" tabindex="-1"><span class="product-wordmark">nintec<span>360</span></span><strong>CRM i control</strong><span>Historial · Estat<br>Següent acció</span><small>En totes les etapes ↗</small></button>')
 panels.append(f'<section class="cycle-panel" id="{prefix}-panel-6" role="tabpanel" aria-labelledby="{prefix}-tab-6" tabindex="0" hidden><div class="cycle-panel-heading"><span class="eyebrow">AL CENTRE / VISIBILITAT DURANT TOT EL CICLE</span><h2>Saps d’on ve cada client i en quin punt està.</h2></div><dl class="cycle-explanation"><div><dt>EL PROBLEMA</dt><dd>Les converses i les campanyes deixen informació dispersa. Costa saber què s’ha fet i què queda pendent.</dd></div><div><dt>QUÈ FA NINTEC360</dt><dd>Registra el canal, l’origen, el resum, l’estat i les accions. Pot actualitzar el CRM i donar context a l’equip.</dd></div><div><dt>QUÈ HI GUANYES</dt><dd>Visibilitat de cada relació comercial, amb informació per decidir on intervenir i quin és el següent pas.</dd></div></dl><p class="cycle-record"><span>AL CRM</span> Origen · Historial · Estat · Responsable · Resultat · Següent acció</p></section>')
 wheel=f'''<div class="cycle-visual"><p class="cycle-visual-label">EL CERCLE NINTEC360 <button type="button" class="cycle-playback-toggle" data-cycle-playback-toggle aria-pressed="false" hidden>Pausar recorregut</button><span data-cycle-static-hint>Tria una etapa ↓</span></p><div class="cycle-wheel" role="tablist" aria-label="Etapes del cicle del client i control"><svg viewBox="0 0 600 560" aria-hidden="true" class="cycle-orbit"><defs><marker id="{prefix}-arrow" markerWidth="6" markerHeight="6" refX="4" refY="3" orient="auto"><path d="M0,0 L5,3 L0,6" fill="none" stroke="#8c76ce" stroke-width="1.2"/></marker></defs><ellipse cx="300" cy="280" rx="204" ry="207" fill="none" stroke="#e0d9f1" stroke-width="1.5"/><g fill="none" stroke="#8c76ce" stroke-width="1.5">{''.join(arcs)}</g><circle cx="300" cy="280" r="122" fill="none" stroke="#ece6f7" stroke-dasharray="3 7"/></svg>{''.join(nodes)}</div><p class="cycle-visual-note"><span aria-hidden="true">↻</span> Les campanyes activen nous contactes.<br>El context es conserva al llarg del cercle.</p></div>'''
 details='<div class="cycle-details">'+''.join(panels)+'<p class="cycle-clarification">El recorregut s’adapta a cada client i a les regles del negoci. No tothom passa per totes les etapes.</p></div>'
 return wheel,details
