const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(__dirname+'/../src/api.js','utf8');
let calls=[],rows=[],status=200,fail=false;
const context={Date,Intl,Set,AbortController,setTimeout,clearTimeout,fetch:async(url,options)=>{calls.push({url,...options,payload:JSON.parse(options.body)});if(fail)throw new Error('offline');const isRPC=url.includes('/rpc/');return {ok:isRPC?status===200:status<400,status,text:async()=>isRPC?JSON.stringify(rows):''}}};
vm.createContext(context);vm.runInContext(source,context);const api=context.NintecAPI;
(async()=>{
 const madrid=api.madridNow(new Date('2026-09-08T22:15:00Z'));assert.equal(madrid.date,'2026-09-09');assert.equal(madrid.minutes,15);
 const winter=api.madridNow(new Date('2026-01-08T22:15:00Z'));assert.equal(winter.minutes,23*60+15);
 const days=api.businessDays(new Date('2026-09-11T08:15:00Z'));assert.equal(days.length,12);assert.equal(days[0].date,'2026-09-11');assert.equal(days[1].date,'2026-09-14');assert.equal(days[0].slots.find(x=>x.time==='11:00').taken,true);assert.equal(days[0].slots.find(x=>x.time==='11:30').taken,false);
 rows=[{data:'2026-09-14',hora:'09:30:00'}];const available=await api.availability(new Date('2026-09-11T08:15:00Z'));assert.equal(available[1].slots.find(x=>x.time==='09:30').taken,true);assert.equal(calls.at(-1).payload._desde,'2026-09-11');assert.ok(calls.at(-1).payload._fins);
 fail=true;await assert.rejects(()=>api.availability());fail=false;
 rows=null;await assert.rejects(()=>api.availability());rows=[{invalid:'bad response'}];await assert.rejects(()=>api.availability());rows=[];
 const contact={nom:'  Prova ',cognoms:'Local ',empresa:'Test',email:'test@example.invalid',telefon:'',missatge:'QA'};
 const future=api.businessDays()[2].date;calls=[];await api.reserve(contact,future,'09:00');assert.equal(calls.length,2);assert.ok(calls[0].url.endsWith('/rpc/get_franges_ocupades'));assert.ok(calls[1].url.endsWith('/reserves_auditoria'));assert.equal(calls[1].payload.nom,'Prova');assert.equal(calls[1].payload.hora,'09:00:00');assert.equal(Object.keys(calls[1].payload).sort().join(','),'cognoms,data,email,empresa,hora,missatge,nom,suggeriment_horari,telefon');
 rows=[{data:future,hora:'09:00:00'}];calls=[];await assert.rejects(()=>api.reserve(contact,future,'09:00'),e=>e.status===409);assert.equal(calls.length,1);rows=[];
 calls=[];await api.reserve(contact,null,null,'  Dijous a la tarda  ');assert.equal(calls.length,1);assert.equal(calls[0].payload.data,null);assert.equal(calls[0].payload.hora,null);assert.equal(calls[0].payload.suggeriment_horari,'Dijous a la tarda');
 await assert.rejects(()=>api.reserve(contact,null,null,''));status=500;await assert.rejects(()=>api.reserve(contact,null,null,'dijous'));status=200;
 calls=[];await api.subscribe(' test@example.invalid ');assert.ok(calls[0].url.endsWith('/leads_compliance'));assert.equal(calls[0].payload.email,'test@example.invalid');
 console.log('PASS: Madrid timezone (summer/winter), 12 business days, one-hour notice, occupied slots, RPC contract, fail-closed availability, invalid responses, fresh recheck, reservation payload, conflict blocks insert, alternative slot payload, failed writes, Compliance payload. All writes used a local fake transport; zero live test submissions.');
})().catch(e=>{console.error(e);process.exitCode=1});
